<script setup>
import { computed, ref } from 'vue'
import { Activity, Archive, ArrowUpRight, BrainCircuit, Check, ChevronDown, CircleX, Clock3, Cpu, GitCompare, Layers3, Plus, RefreshCw, Rocket, Search, Terminal, X } from 'lucide-vue-next'
import Chart from '../components/Chart.vue'
import Modal from '../components/Modal.vue'
import { api, act, canEdit, dateTime, kinds, number, notify, refresh, state, statuses, trackJob } from '../state'

const showTrain = ref(false)
const submitting = ref(false)
const selectedModel = ref(null)
const query = ref('')
const form = ref({ name: '', dataset_id: '', kind: 'ensemble', horizon: 24, epochs: 12 })
const filtered = computed(() => state.models.filter(model => !query.value || `${model.name} ${kinds[model.kind]}`.toLowerCase().includes(query.value.toLowerCase())))
const trainingJobs = computed(() => state.jobs.filter(job => job.kind === 'train'))
const historyOption = computed(() => ({ color: ['#21876b', '#a8c2b3'], grid: { left: 42, right: 18, top: 22, bottom: 32 }, tooltip: { trigger: 'axis' }, legend: { bottom: 0, textStyle: { fontSize: 10 } }, xAxis: { type: 'category', data: selectedModel.value?.metrics?.history?.map(item => item.step) || [] }, yAxis: { type: 'value', name: 'MSE', splitLine: { lineStyle: { type: 'dashed', color: '#edf1ee' } } }, series: [{ name: '训练', type: 'line', symbol: 'none', data: selectedModel.value?.metrics?.history?.map(item => item.train_loss) || [] }, { name: '验证', type: 'line', symbol: 'none', data: selectedModel.value?.metrics?.history?.map(item => item.val_loss) || [] }] }))
function openTrain() { form.value = { name: `新模型 · ${new Date().toLocaleDateString('zh-CN')}`, dataset_id: state.datasets[0]?.id || '', kind: 'ensemble', horizon: 24, epochs: 12 }; showTrain.value = true }
async function train() { if (submitting.value) return; submitting.value = true; const result = await act(() => api('/models/train', { method: 'POST', body: form.value })); if (result) { showTrain.value = false; trackJob(result.job_id, '模型训练'); notify('训练任务已提交'); await act(refresh) }; submitting.value = false }
async function publish(model) { const result = await act(() => api(`/models/${model.id}/publish`, { method: 'POST' })); if (result) { notify('模型已上线'); await refresh(); if (selectedModel.value?.id === model.id) selectedModel.value = state.models.find(item => item.id === model.id) } }
async function inspect(model) { selectedModel.value = state.models.find(item => item.id === model.id) || model }
</script>

<template>
  <div class="page-intro"><div><div class="eyebrow">MODEL OPERATIONS</div><h1>训练与模型<span class="title-dot"></span></h1><p>让每一个模型版本都可追溯、可比较、可回滚。</p></div><button v-if="canEdit()" class="button primary" @click="openTrain"><Plus :size="17" />发起训练</button></div>
  <div class="model-summary"><div class="summary-lead"><div class="summary-icon"><BrainCircuit :size="22" /></div><div><span>当前上线模型</span><strong>{{ state.models.find(item => item.status === 'active')?.name || '尚未上线' }}</strong><small>{{ state.models.find(item => item.status === 'active') ? kinds[state.models.find(item => item.status === 'active').kind] : '完成一次训练即可生成候选模型' }}</small></div></div><div><span>版本总数</span><strong>{{ state.models.length }}</strong></div><div><span>训练任务</span><strong>{{ trainingJobs.length }}</strong></div><div><span>计算服务</span><strong :class="state.summary?.worker_alive ? 'green-text' : 'amber-text'">{{ state.summary?.worker_alive ? '在线' : '离线' }}</strong></div></div>
  <section class="card table-card"><div class="table-toolbar"><div class="search-box"><Search :size="16" /><input v-model="query" placeholder="搜索模型名称或算法类型" /></div><div class="toolbar-note"><Clock3 :size="14" />训练按时间切分，测试集标签不参与校准</div></div><div class="table-wrap"><table><thead><tr><th>模型版本</th><th>类型</th><th>状态</th><th>预测步长</th><th>测试集 MAE</th><th>覆盖率</th><th>创建时间</th><th></th></tr></thead><tbody><tr v-for="model in filtered" :key="model.id" @click="inspect(model)"><td><div class="primary-cell"><span class="model-icon"><BrainCircuit :size="15" /></span><div><strong>{{ model.name }}</strong><small>{{ model.id }} · 数据 v{{ model.dataset_version }}</small></div></div></td><td><span class="type-label"><Layers3 :size="14" />{{ kinds[model.kind] }}</span></td><td><span :class="['tag', model.status === 'active' ? 'green' : model.status === 'training' ? 'blue' : model.status === 'failed' ? 'red' : 'neutral']"><i></i>{{ statuses[model.status] }}</span></td><td>{{ model.horizon }} 步</td><td><strong>{{ number(model.metrics?.mae, 2) }}</strong> <small>kW</small></td><td>{{ number(model.metrics?.coverage, 1) }}%</td><td class="muted">{{ dateTime(model.created_at) }}</td><td><div class="row-actions"><button class="icon-button" aria-label="查看模型详情" title="查看详情" @click.stop="inspect(model)"><ArrowUpRight :size="16" /></button><button v-if="['ready', 'archived'].includes(model.status) && state.user.role === 'admin'" class="button table-button" @click.stop="publish(model)"><Rocket :size="14" />上线</button></div></td></tr><tr v-if="!filtered.length"><td colspan="8" class="empty-state"><BrainCircuit :size="26" /><strong>还没有模型版本</strong><span>导入数据后发起一次训练。</span></td></tr></tbody></table></div></section>
  <section class="jobs-section"><div class="section-heading"><div><h2>最近训练任务</h2><p>训练在独立计算进程中执行，页面每 4 秒更新状态</p></div></div><div class="job-grid"><div v-for="job in trainingJobs.slice(0, 4)" :key="job.id" class="job-card"><div class="job-card-head"><span :class="['job-status', job.status]"><i></i>{{ statuses[job.status] }}</span><span class="mono">{{ dateTime(job.created_at) }}</span></div><strong>{{ state.models.find(model => model.id === job.model_id)?.name || '训练任务' }}</strong><div class="progress-track"><i :style="{ width: job.progress + '%' }"></i></div><div class="job-foot"><span>{{ job.progress }}%</span><span>{{ job.logs?.at(-1)?.message }}</span></div></div><div v-if="!trainingJobs.length" class="empty-inline"><Terminal :size="16" />暂无训练任务</div></div></section>
  <Modal v-if="showTrain" title="发起模型训练" @close="showTrain = false"><form class="form-stack" @submit.prevent="train"><label>模型名称<input v-model="form.name" required /></label><label>训练数据集<select v-model="form.dataset_id" required><option disabled value="">请选择数据集</option><option v-for="dataset in state.datasets" :key="dataset.id" :value="dataset.id">{{ dataset.name }} · {{ dataset.rows }} 条</option></select></label><label>模型类型<select v-model="form.kind"><option value="ensemble">集成树 + 残差校准（CPU 友好）</option><option value="hybrid" :disabled="!state.settings?.hybrid_available">SSM + 稀疏上下文注意力（PyTorch）</option><option value="seasonal">季节朴素基线（对照）</option></select></label><div class="form-grid"><label>预测步数<input v-model.number="form.horizon" type="number" min="2" max="168" /></label><label v-if="form.kind === 'hybrid'">训练轮次<input v-model.number="form.epochs" type="number" min="2" max="100" /></label></div><div class="note-box"><Cpu :size="16" /><p>模型会按时间划分训练、验证、独立校准和测试区间；训练完成后处于“待上线”，需要管理员确认。</p></div><div class="modal-actions"><button type="button" class="button ghost" @click="showTrain = false">取消</button><button class="button primary" :disabled="!form.dataset_id || submitting"><BrainCircuit :size="16" />提交训练</button></div></form></Modal>
  <Modal v-if="selectedModel" :title="`${selectedModel.name} · 模型详情`" wide @close="selectedModel = null"><div class="detail-head"><div><span :class="['tag', selectedModel.status === 'active' ? 'green' : 'neutral']">{{ statuses[selectedModel.status] }}</span><p>{{ kinds[selectedModel.kind] }} · 预测 {{ selectedModel.horizon }} 步 · 数据版本 v{{ selectedModel.dataset_version }}</p></div><button v-if="['ready', 'archived'].includes(selectedModel.status) && state.user.role === 'admin'" class="button primary" @click="publish(selectedModel)"><Rocket :size="15" />上线</button></div><div class="model-detail-grid"><div class="metric-card mini"><small>MAE</small><strong>{{ number(selectedModel.metrics?.mae, 2) }} <span>kW</span></strong></div><div class="metric-card mini"><small>RMSE</small><strong>{{ number(selectedModel.metrics?.rmse, 2) }} <span>kW</span></strong></div><div class="metric-card mini"><small>覆盖率</small><strong>{{ number(selectedModel.metrics?.coverage, 1) }} <span>%</span></strong></div><div class="metric-card mini"><small>CRPS</small><strong>{{ number(selectedModel.metrics?.crps, 2) }} <span>kW</span></strong></div></div><div v-if="selectedModel.metrics?.candidate_review" class="note-box"><p>自适应候选同窗口复评：旧模型 MAE {{ number(selectedModel.metrics.candidate_review.previous_mae, 2) }} kW，候选 MAE {{ number(selectedModel.metrics.candidate_review.candidate_mae, 2) }} kW；{{ selectedModel.metrics.candidate_review.recommended ? '候选误差更低' : '暂不建议替换' }}。请审核再上线，归档版本可以重新发布回滚。</p></div><Chart :option="historyOption" :height="260" /><div class="detail-note"><strong>评估说明</strong><span>{{ selectedModel.metrics?.interval_method }}</span></div></Modal>
</template>
