<script setup>
import { computed, ref, watch } from 'vue'
import { Activity, RefreshCw, Save, ShieldCheck, Terminal } from 'lucide-vue-next'
import Modal from '../components/Modal.vue'
import { act, api, canEdit, dateTime, notify, number, refresh, state, statuses } from '../state'
const policy = ref({ ...state.settings?.learning })
const loaded = ref(!!state.settings)
const saving = ref(false)
const selectedJob = ref(null)
const job = computed(() => state.jobs.find(item => item.id === selectedJob.value))
watch(() => state.settings, value => { if (!loaded.value && value) { policy.value = { ...value.learning }; loaded.value = true } })
async function save() { saving.value = true; await act(async () => { await api('/settings/learning', { method: 'PUT', body: policy.value }); notify('策略已保存；候选模型仍需人工上线'); await refresh() }); saving.value = false }
async function cancel(item) { await act(async () => { await api(`/jobs/${item.id}/cancel`, { method: 'POST' }); await refresh(); notify('排队任务已取消') }) }
</script>
<template><div class="page-intro"><div><div class="eyebrow">CONTINUOUS OPERATIONS</div><h1>运行监测<span class="title-dot"></span></h1><p>数据回流后重新检验，让模型更新保持可控。</p></div><button class="button ghost" @click="act(refresh)"><RefreshCw :size="16" />刷新状态</button></div><div class="context-banner"><Activity :size="22" /><div><strong>{{ state.settings?.worker_alive ? '独立计算服务在线' : '计算服务离线，请重启应用' }}</strong><span>数据追加 → 实际值匹配 → 误差 / 漂移监测 → 候选重训 → 人工发布</span></div><span class="tag neutral">4 秒界面轮询</span></div>
  <div class="two-column"><section class="card"><div class="card-heading"><div><h2>自适应学习策略</h2><p>由数据到达触发的批量重训，不是逐点在线学习</p></div><ShieldCheck :size="20" /></div><form class="form-stack" @submit.prevent="save"><fieldset :disabled="state.user.role !== 'admin'"><label class="switch-row"><div><strong>自动滚动预测</strong><small>追加数据后使用当前上线版本预测</small></div><input v-model="policy.auto_forecast" type="checkbox" role="switch" /></label><label class="switch-row"><div><strong>受控自适应重训</strong><small>达到门槛后生成候选，不替换线上模型</small></div><input v-model="policy.enabled" type="checkbox" role="switch" /></label><div class="form-grid"><label>最少新增观测点<input v-model.number="policy.minimum_points" type="number" min="2" max="10000" required /></label><label>重训冷却时长（小时）<input v-model.number="policy.cooldown_hours" type="number" min="0" max="720" step="0.5" required /></label></div><label>回流 WAPE 触发阈值（%）<input v-model.number="policy.error_threshold" type="number" min="0.1" max="500" step="0.1" required /></label><div class="note-box"><p>新增样本数与冷却期同时满足后，WAPE 超阈值或均值偏移分数大于 2.5 才触发重训。无回流标签时不伪造误差。均值偏移仅作提示，不是正式统计检验。</p></div><button class="button primary" :disabled="saving"><Save :size="16" />{{ saving ? '保存中…' : '保存策略' }}</button></fieldset></form></section><section class="card"><div class="card-heading"><div><h2>真实值回流监测</h2><p>最近 20 次未来预测，按时间戳去重</p></div><a class="text-link" href="#data">追加数据 →</a></div><div v-if="!state.settings?.monitors?.length" class="empty-state"><Activity :size="28" /><strong>等待数据更新</strong><span>在数据管理追加 CSV，或为演示数据追加观测。</span></div><div v-for="item in state.settings?.monitors" :key="item.dataset_id" class="monitor-item"><div class="detail-head"><strong>{{ state.datasets.find(data => data.id === item.dataset_id)?.name }}</strong><span :class="['tag', item.drift_warning ? 'amber' : 'green']">{{ item.drift_warning ? '偏移提醒' : '已更新' }}</span></div><div class="quality-grid"><div><small>已匹配观测</small><strong>{{ item.observed_points }}</strong></div><div><small>回流 WAPE</small><strong>{{ number(item.recent_wape) }}%</strong></div><div><small>均值偏移分数</small><strong>{{ number(item.mean_shift_z, 2) }}</strong></div></div><p class="muted">数据 v{{ item.dataset_version }} · {{ dateTime(item.updated_at) }}</p></div></section></div>
  <div class="section-heading"><h2>计算任务</h2><span class="muted">显示最近 50 个任务，运行中的任务不可强制取消</span></div><section class="card table-card"><div class="table-wrap"><table><thead><tr><th>任务</th><th>状态</th><th>进度</th><th>最近消息</th><th>创建时间</th><th>操作</th></tr></thead><tbody><tr v-for="item in state.jobs" :key="item.id"><td><strong>{{ {train:'模型训练',predict:'在线推理',refresh:'数据更新'}[item.kind] }}</strong><small class="cell-sub mono">{{ item.id }}</small></td><td><span :class="['tag', item.status === 'failed' ? 'red' : item.status === 'success' ? 'green' : 'neutral']">{{ statuses[item.status] }}</span></td><td>{{ item.progress }}%</td><td class="log-summary">{{ item.logs?.at(-1)?.message || '等待工作进程' }}</td><td>{{ dateTime(item.created_at) }}</td><td><div class="row-actions"><button class="button table-button" @click="selectedJob = item.id"><Terminal :size="14" />日志</button><button v-if="item.status === 'pending' && canEdit()" class="text-link danger" @click="cancel(item)">取消</button></div></td></tr><tr v-if="!state.jobs.length"><td colspan="6" class="empty-state">暂无任务</td></tr></tbody></table></div></section>
  <Modal v-if="job" title="任务日志" wide @close="selectedJob = null"><div class="log-view"><p v-for="(entry,index) in job.logs" :key="index"><time>{{ dateTime(entry.time || entry.at) }}</time> {{ entry.message }}</p><p v-if="job.result?.error" class="error-text">{{ job.result.error }}</p><p v-if="!job.logs?.length">等待任务开始…</p></div></Modal>
</template>
