<script setup>
import { onMounted, ref } from 'vue'
import { LockKeyhole, Plus, Server, Users } from 'lucide-vue-next'
import Modal from '../components/Modal.vue'
import { act, api, dateTime, notify, roles, state } from '../state'
const users = ref([])
const showUser = ref(false)
const saving = ref(false)
const password = ref('')
const form = ref({ username: '', password: '', role: 'operator' })
async function loadUsers() { if (state.user.role === 'admin') users.value = await api('/users') }
onMounted(() => act(loadUsers))
async function createUser() { saving.value = true; await act(async () => { await api('/users', { method: 'POST', body: form.value }); await loadUsers(); showUser.value = false; form.value = { username: '', password: '', role: 'operator' }; notify('用户已创建') }); saving.value = false }
async function changePassword() { saving.value = true; await act(async () => { await api('/auth/password', { method: 'POST', body: { username: state.user.username, password: password.value } }); password.value = ''; notify('密码已更新') }); saving.value = false }
</script>
<template><div class="page-intro"><div><div class="eyebrow">WORKSPACE SETTINGS</div><h1>系统设置<span class="title-dot"></span></h1><p>部署环境、访问权限与账号安全。</p></div><span class="tag neutral">GridCast Studio 1.0</span></div><div class="two-column"><section class="card"><div class="card-heading"><h2><Server :size="18" /> 运行环境</h2></div><dl class="key-values"><div><dt>部署模式</dt><dd>{{ state.settings?.mode === 'cloud' ? '云端 · 单实例' : '本地工作站' }}</dd></div><div><dt>数据存储</dt><dd>SQLite + 本机版本文件</dd></div><div><dt>计算服务</dt><dd>{{ state.settings?.worker_alive ? '独立工作进程在线' : '离线' }}</dd></div><div><dt>混合模型运行时</dt><dd>{{ state.settings?.hybrid_available ? 'PyTorch 已安装' : '未安装（集成模型可用）' }}</dd></div><div><dt>业务时区</dt><dd>Asia/Shanghai</dd></div><div><dt>前端刷新周期</dt><dd>4 秒</dd></div></dl><div class="note-box"><p>本地 / 云端复用同一应用，通过环境变量和容器部署切换；不是跨设备自动同步。云端需配置 HTTPS、初始化令牌和持久化存储。原型仅支持一个 API 实例。</p></div></section><section class="card"><div class="card-heading"><h2><LockKeyhole :size="18" /> 当前账号</h2><span class="tag green">{{ roles[state.user.role] }}</span></div><p class="body-copy">已登录为 <strong>{{ state.user.username }}</strong>。会话有效期 8 小时，请勿共享账号。</p><form class="form-stack" @submit.prevent="changePassword"><label>新密码<input v-model="password" type="password" minlength="8" maxlength="72" autocomplete="new-password" required placeholder="至少 8 个字符" /></label><button class="button primary" :disabled="saving">更新自己的密码</button></form><div class="note-box"><p>原型不提供邮件找回或自动注销其他会话；部署到公网前应完成备份、访问审计和安全加固。</p></div></section></div><template v-if="state.user.role === 'admin'"><div class="section-heading"><h2><Users :size="18" /> 用户与权限</h2><button class="button primary" @click="showUser = true"><Plus :size="16" />新增用户</button></div><section class="card table-card"><div class="table-wrap"><table><thead><tr><th>用户名</th><th>角色</th><th>权限范围</th><th>创建时间</th></tr></thead><tbody><tr v-for="item in users" :key="item.id"><td><strong>{{ item.username }}</strong></td><td>{{ roles[item.role] }}</td><td>{{ item.role === 'admin' ? '全部功能、发布、用户管理' : item.role === 'engineer' ? '数据导入、追加、训练与预测' : '查看数据、预测与导出' }}</td><td>{{ dateTime(item.created_at) }}</td></tr></tbody></table></div></section></template><Modal v-if="showUser" title="新增用户" @close="showUser = false"><form class="form-stack" @submit.prevent="createUser"><label>用户名<input v-model="form.username" pattern="[a-zA-Z0-9_\-]{3,40}" required autocomplete="off" /></label><label>初始密码<input v-model="form.password" type="password" minlength="8" required autocomplete="new-password" /></label><label>角色<select v-model="form.role"><option value="operator">业务运营</option><option value="engineer">算法工程师</option><option value="admin">系统管理员</option></select></label><div class="modal-actions"><button class="button primary" :disabled="saving">创建用户</button></div></form></Modal></template>
